## Sampling rate
DAC_VRVQ_FeatureDenoise.sample_rate: 48000
Discriminator.sample_rate: 48000

# Data
batch_size: 16
# train/AudioDataset_EARS_Paired.duration: 0.38
train/AudioDataset_EARS_Paired.duration: 0.8
train/AudioDataset_EARS_Paired.n_examples: 10000000


val_batch_size: 4
val/AudioDataset_EARS_Paired.duration: 3.0
val/AudioDataset_EARS_Paired.n_examples: 32

# batch_size_test: 1
# test/AudioDataset.duration: 10.0
# test/build_transform.augment_prob: 0.0
# test/AudioDataset.n_examples: 100  ## this setting
# test/AudioDataset.n_examples: 40  ## just for temp
# test/AudioDatasetNoisyClean.duration: 3.0
# test/AudioDatasetNoisyClean.duration: 1.5
# test/AudioDatasetNoisyClean.n_examples: 150

# AudioLoader.shuffle: true
# AudioDataset.without_replacement: true

AudioLoader_EARS_Paired.shuffle: true
AudioDataset_EARS_Paired.without_replacement: true

train/build_dataset.folders:
        clean:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/train/clean

        noisy:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/train/noisy


val/build_dataset.folders:
        clean:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/valid/clean
        noisy:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/valid/noisy

test/build_loader.folders:
        clean:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/test/clean

        noisy:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/test/noisy

test_mamba/build_loader.folders:
        clean:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/test/clean

        est_mamba:
                - /data2/yoongi/dataset/EARS_dataset/ears_benchmark/ears_wham/EARS-WHAM/test_semamba/16000

# test/build_dataset.folders:
#         speech_clean:
#                 # - /data/yoongidata/data/voicebank-demand-48k-encodec-3sec-24kbps/clean_testset_wav
#                 - /data/yoongidata/data/voicebank_demand/clean_testset_wav

#         speech_noisy:
#                 # - /data/yoongidata/data/voicebank-demand-48k-encodec-3sec-24kbps/noisy_testset_wav
#                 - /data/yoongidata/data/voicebank_demand/noisy_testset_wav

